### ISSUE TITLE
decisiontable-quarkus-example, Powershell: Invoke-WebRequest : Cannot bind parameter 'Headers'

### ISSUE THREAD

**Issue by maxloopinmok** [apache/incubator-kie-examples#838]
I'm trying out the code for windows from "POST /find-approved" from the webpage [decisiontable-quarkus-example](https://github.com/kiegroup/kogito-examples/tree/stable/decisiontable-quarkus-example):

`curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d "{\"maxAmount\":5000,\"loanApplications\":[{\"id\":\"ABC10001\",\"amount\":2000,\"deposit\":100,\"applicant\":{\"age\":45,\"name\":\"John\"}}, {\"id\":\"ABC10002\",\"amount\":5000,\"deposit\":100,\"applicant\":{\"age\":25,\"name\":\"Paul\"}}, {\"id\":\"ABC10015\",\"amount\":1000,\"deposit\":100,\"applicant\":{\"age\":12,\"name\":\"George\"}}]}" http://localhost:8080/find-approved`

But I get this error:

```
Invoke-WebRequest : Cannot bind parameter 'Headers'.
Cannot convert the "Accept: application/json" value of
type "System.String" to type
"System.Collections.IDictionary".
At line:2 char:17
+ curl -X POST -H "Accept: application/json" -H
"Content-Type: applicat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke
   -WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessa
   ge,Microsoft.PowerShell.Commands.InvokeWebRequestComma
  nd
```

May I know how to make it work?  What went wrong?

**Comment by ricardozanini** [comment]
@tarilabs can you take a look?

**Comment by ricardozanini** [comment]
@maxloosmu can you try removing the header "accept" from your command line?

**Comment by tarilabs** [comment]
https://github.com/kiegroup/kogito-examples/issues/838#issuecomment-894144309 looks affecting the DRL, not DMN, so I'm not entirely sure here. cc/ @danielezonca

**Comment by danielezonca** [comment]
@maxloosmu 
I think the problem is that in PowerShell `curl` seems to be an alias of `Invoke-WebRequest` that has a different syntax.
Looking at this [SO answer](https://stackoverflow.com/a/48521023) there are two possible solutions: convert the command to `Invoke-WebRequest` (or `Invoke-RestRequest`) syntax or download and use `curl.exe` binary directly.
The first solution seems to be the most idiomatic for a PowerShell user but I don't know that tool so I don't know how to help with the syntax.

**Comment by maxloopinmok** [comment]
I've tried both `Invoke-RestMethod` and `Invoke-WebRequest`.  Both do not work.  I get an error when I run `test.ps1`, which can use both commands.  I can't attach the file here because of github's restrictions, but I've copied the relevant code into `test.txt` and attached the file here.  
[test.txt](https://github.com/kiegroup/kogito-examples/files/6947022/test.txt)


```
Invoke-RestMethod : com.fasterxml.jackson.databind.exc.Mism
atchedInputException: Cannot deserialize value of type `jav
a.util.ArrayList&lt;org.kie.kogito.queries.LoanApplication&
gt;` from String value (token `JsonToken.VALUE_STRING`)
 at [Source:
(io.undertow.servlet.spec.ServletInputStreamImpl); line:
2, column: 26] (through reference chain: org.kie.kogito.que
ries.LoanUnit[&quot;loanApplications&quot;])
At C:\Users\Max\src\kogito\kogito\ruleunit-quarkus-example\
test.ps1:27 char:11
+ $result = Invoke-RestMethod -Method Post -Uri
$post_data_url -Headers ...
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Ne
   t.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod],
  WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseExceptio
   n,Microsoft.PowerShell.Commands.InvokeRestMethodComman
  d
```

**Comment by maxloopinmok** [comment]
I have a feeling that Kogito's examples are not fully designed for Powershell.  Is it ok to use Powershell to test Kogito's examples?

**Comment by tarilabs** [comment]
With reference to the original issue description here: https://github.com/kiegroup/kogito-examples/issues/838#issue-961822217

The example works just fine on Windows, as demonstrated by this screenshot:
![image](https://user-images.githubusercontent.com/1699252/128625885-ec5b9fc5-a2f2-4949-bc62-746eda3f7930.png)

If you are using PowerShell and not the default Command Prompt on Win10, you need to:
- Maintain proper escaping for PowerShell
- Use the `curl.exe` binary, not the alias of PowerShell
edit: to be clear Win10 ships with `curl.exe` out of the box, without any need of manual download or install.
I verified this on my personal Win10 machine.
Ref: https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/

You should be able to achieve easily the first item by replacing the external wrapping by using single quote instead of double-quote, eg from `"`  to `'`.
You should be able to achieve easily the second item by using explicitly `curl.exe` in a PowerShell.

e.g.:
from
```
curl ... -d "{\"maxAmount\":5000, ... }" http://localhost:8080
```
to
```
curl.exe ... -d '{\"maxAmount\":5000, ... }' http://localhost:8080
```

So in conclusion you need to transform the example command to a PowerShell compatible command on your side, e.g.:
```
curl.exe -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d '{\"maxAmount\":5000,\"loanApplications\":[{\"id\":\"ABC10001\",\"amount\":2000,\"deposit\":100,\"applicant\":{\"age\":45,\"name\":\"John\"}}, {\"id\":\"ABC10002\",\"amount\":5000,\"deposit\":100,\"applicant\":{\"age\":25,\"name\":\"Paul\"}}, {\"id\":\"ABC10015\",\"amount\":1000,\"deposit\":100,\"applicant\":{\"age\":12,\"name\":\"George\"}}]}' http://localhost:8080/find-approved
```

Demonstration screenshot:
![image](https://user-images.githubusercontent.com/1699252/128626013-a6154ff0-c783-4103-ada8-84c434368273.png)


Finally, it seems you are interested in decision tables, but you are checking out legacy dt in example `decisiontable-quarkus-example`; you might be interested to know that in Drools, Kogito, etc. we already support [DMN open standard](https://drools.org/learn/dmn.html) including as well modern decision table and visual notation, we include both a [dedicated Quarkus guide](https://quarkus.io/guides/kogito-dmn) and many examples [such as `dmn-quarkus-example`](https://github.com/kiegroup/kogito-examples/tree/stable/dmn-quarkus-example).

**Comment by maxloopinmok** [comment]
@tarilabs , thanks!  the commands work.
